// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApp.Infrastructure.Persistence;

#nullable disable

namespace TodoApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TodoAppDbContext))]
    partial class TodoAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TodoApp.Domain.Entities.TodoTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("70e5fc52-79e6-476c-ba95-4bf25e2dd48e"),
                            Description = "This is about task title 1 description.",
                            DueDate = new DateTime(2025, 6, 21, 13, 2, 7, 932, DateTimeKind.Utc).AddTicks(9402),
                            IsCompleted = false,
                            Title = "Task title 1"
                        },
                        new
                        {
                            Id = new Guid("a5a4fc1d-3d3d-4c21-ab43-1bd28bb8e235"),
                            Description = "This is about task title 2 description.",
                            DueDate = new DateTime(2025, 6, 21, 13, 2, 7, 932, DateTimeKind.Utc).AddTicks(9581),
                            IsCompleted = false,
                            Title = "Task title 2"
                        },
                        new
                        {
                            Id = new Guid("eed4592f-b415-46d2-b971-b5a39be295aa"),
                            Description = "This is about task title 3 description.",
                            DueDate = new DateTime(2025, 6, 21, 13, 2, 7, 932, DateTimeKind.Utc).AddTicks(9585),
                            IsCompleted = false,
                            Title = "Task title 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
